### PR TITLE
Add missing setBan method

### PR DESCRIPTION
**Pull request by jay-emm-jee**
Adds the missing setBan method.

### CODE REVIEW

**Comment by quang-m-nguyen** [comment]
@LucidLunacy thanks for doing this! can you please resolve the conflicts first and I will review it again

**Review by quang-m-nguyen — CHANGES_REQUESTED** [review]
minor.  see comment

**Review by quang-m-nguyen — APPROVED** [review]
merge away.  thanks!

**Comment by jay-emm-jee** [comment]
Happy to help. Keep up the awesome work. :+1:

**Pull request merged**
